static_map: false
rolling_window: true
width: 3.0
height: 3.0
resolution: 0.1
map_type: costmap
track_unknown_space: true
transform_tolerance: 0.3
always_send_full_costmap: true

# inflation layer
inflation_radius: 1.0
cost_scaling_factor: 5.0
